### ISSUE TITLE
This buildpack fails detection if the "gem puma" line is starts with spaces in the Gemfile.

### ISSUE THREAD

**Issue by genevieve** [paketo-buildpacks/puma#83]
I have a Gemfile like:
```
source "$SOURCE" do
  gem 'rails', '~> 6.0.3', '>= 6.0.3.2'
  gem 'puma', '~> 4.1'
...
end
```

And this buildpack fails to detect. When I remove the spaces before `gem puma` in the file, the buildpack works.

**Comment by ryanmoran** [comment]
Looks like we have a caret anchor in our regex that probably isn't necessary: https://github.com/paketo-buildpacks/puma/blob/bd649f8f31fe8558da568b86c37cc1d3217c2bb9/gemfile_parser.go#L28
